apiVersion: garden.io/v1
kind: Project
name: garden-grafana-stack

defaultEnvironment: local

variables:
  userNamespace: garden-grafana-stack

environments:
  - name: local
    defaultNamespace: ${var.userNamespace}
    variables:
      hostname: local.demo.garden

providers:
  - name: local-kubernetes
    environments: [local]
