kind: Deploy
type: helm
name: grafana

dependencies:
  - deploy.loki

spec:
  chart:
    name: grafana
    repo: https://grafana.github.io/helm-charts
    version: 8.12.1
  values:
    ingress:
      enabled: true
      hosts:
        - grafana.${var.hostname}
    grafana.ini:
      auth.anonymous:
        enabled: true
        org_role: Admin
      auth:
        disable_login_form: true
      log:
        level: debug
        mode: console
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Loki
            type: loki
            url: http://loki:3100
            access: proxy
            isDefault: true
